version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 15433:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=starter
      - POSTGRES_DB=starter_db
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=cyberhck
      - INFLUXDB_ADMIN_PASSWORD=secret
      - INFLUXDB_DB=monitoring
    ports:
      - 8086:8086 # http api
      - 8083:8083 # admin interface

  chronograf:
    container_name: chronograf
    image: chronograf
    environment:
      - influxdb-url=influxdb:8086
    ports:
      - 18888:8888

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,raintank-worldping-app,digrich-bubblechart-panel,corpglory-progresslist-panel,flant-statusmap-panel
    ports:
      - 3000:3000
  adminer:
      image: adminer
      ports:
        - 8081:8080
